//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checksum.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Checksum.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_4Z7907551R_MultiRangeChecksumFunction_0x8ABAB4 {
            get {
                object obj = ResourceManager.GetObject("Mask_4Z7907551R_MultiRangeChecksumFunction_0x8ABAB4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_4Z7907551R_MultiRangeChecksumFunctionValue_0x8ABC40 {
            get {
                object obj = ResourceManager.GetObject("Mask_4Z7907551R_MultiRangeChecksumFunctionValue_0x8ABC40", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_8D0907551C_MultiPointChecksumFunction_0x86DA62 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551C_MultiPointChecksumFunction_0x86DA62", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_8D0907551C_RollingChecksumRanges_0x86C094 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551C_RollingChecksumRanges_0x86C094", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_8D0907551K_RollingChecksumValueInit_0x890742 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551K_RollingChecksumValueInit_0x890742", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Head {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Head", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Tail {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Tail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_MultiPointChecksumCalculationFunction_0x87C532 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_MultiPointChecksumCalculationFunction_0x87C532", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_MultiPointChecksumFunction_0x87CA3E {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_MultiPointChecksumFunction_0x87CA3E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_RollingChecksumRanges_0x87AB80 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_RollingChecksumRanges_0x87AB80", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_RollingChecksumSeedsFunction_0x87A94A {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_RollingChecksumSeedsFunction_0x87A94A", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_4Z7907551R_MultiRangeChecksumFunction_0x8ABAB4 {
            get {
                object obj = ResourceManager.GetObject("Pattern_4Z7907551R_MultiRangeChecksumFunction_0x8ABAB4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_4Z7907551R_MultiRangeChecksumFunctionValue_0x8ABC40 {
            get {
                object obj = ResourceManager.GetObject("Pattern_4Z7907551R_MultiRangeChecksumFunctionValue_0x8ABC40", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_8D0907551C_MultiPointChecksumFunction_0x86DA62 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551C_MultiPointChecksumFunction_0x86DA62", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_8D0907551C_RollingChecksumRanges_0x86C094 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551C_RollingChecksumRanges_0x86C094", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_8D0907551K_RollingChecksumValueInit_0x890742 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551K_RollingChecksumValueInit_0x890742", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Head {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Head", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Tail {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Tail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_MultiPointChecksumCalculationFunction_0x87C532 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_MultiPointChecksumCalculationFunction_0x87C532", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_MultiPointChecksumFunction_0x87CA3E {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_MultiPointChecksumFunction_0x87CA3E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_RollingChecksumRanges_0x87AB80 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_RollingChecksumRanges_0x87AB80", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_RollingChecksumSeedsFunction_0x87A94A {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_RollingChecksumSeedsFunction_0x87A94A", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
